### ISSUE TITLE
Guidance on HandlingMissesUsing

### ISSUE THREAD

**Issue by malclear** [liquidprojections/LiquidProjections#120]
I'm wondering what guidance there might be on recreating missing projections which are based on a series of events. If, for example, a projection is removed due to an entity's representation no longer being required, followed by (typically rare) its return to relevance, how can the projection be rebuilt? There may be 3 or 8 events in the stream that are needed in order to recreate that view.
I'm thinking of using HandlingMissesUsing. Would it be feasible to create a new instance of the projector special for a single entity?

**Comment by dennisdoomen** [comment]
Since LP is opinionated and not a framework, you have a couple of options, all of which you have to handle yourself. 
* You can decide to not actually delete the projection when it's no longer required, and instead just soft-delete it (i.e. use a flag)
* From inside the event handling code in the projector, take a direct dependency on the event store, load the entire stream and push the events through yourself, after which you continue where you left off.

**Comment by malclear** [comment]
Thank you.
